// CertApi.Core/Resources/CertValidationMessages.Designer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertApi.Core.Resources; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class CertValidationMessages {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal CertValidationMessages() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CertApi.Core.Resources.CertValidationMessages", typeof(CertValidationMessages).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Async processor returned {0} errors.
    /// </summary>
    internal static string AsyncProcessorReturned {
        get {
            return ResourceManager.GetString("AsyncProcessorReturned", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Async validation complete. Total errors: {0}.
    /// </summary>
    internal static string AsyncValidationComplete {
        get {
            return ResourceManager.GetString("AsyncValidationComplete", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Async validation mode: {0}, AggregateAllErrors: {1}.
    /// </summary>
    internal static string AsyncValidationMode {
        get {
            return ResourceManager.GetString("AsyncValidationMode", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Executing async processor: {0}.
    /// </summary>
    internal static string ExecutingAsyncProcessor {
        get {
            return ResourceManager.GetString("ExecutingAsyncProcessor", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Executing processor: {0}.
    /// </summary>
    internal static string ExecutingProcessor {
        get {
            return ResourceManager.GetString("ExecutingProcessor", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to No processors in validation chain.
    /// </summary>
    internal static string NoProcessors {
        get {
            return ResourceManager.GetString("NoProcessors", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to No processors in async validation chain.
    /// </summary>
    internal static string NoProcessorsAsync {
        get {
            return ResourceManager.GetString("NoProcessorsAsync", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Processor returned {0} errors.
    /// </summary>
    internal static string ProcessorReturned {
        get {
            return ResourceManager.GetString("ProcessorReturned", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Starting async validation for {0}.
    /// </summary>
    internal static string StartingAsyncValidation {
        get {
            return ResourceManager.GetString("StartingAsyncValidation", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Starting validation for {0}.
    /// </summary>
    internal static string StartingValidation {
        get {
            return ResourceManager.GetString("StartingValidation", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Stopping async validation due to strict mode error.
    /// </summary>
    internal static string StoppingAsyncValidation {
        get {
            return ResourceManager.GetString("StoppingAsyncValidation", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Stopping validation due to strict mode error.
    /// </summary>
    internal static string StoppingValidation {
        get {
            return ResourceManager.GetString("StoppingValidation", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Validation complete. Total errors: {0}.
    /// </summary>
    internal static string ValidationComplete {
        get {
            return ResourceManager.GetString("ValidationComplete", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Validation mode: {0}, AggregateAllErrors: {1}.
    /// </summary>
    internal static string ValidationMode {
        get {
            return ResourceManager.GetString("ValidationMode", resourceCulture);
        }
    }
}
